FROM docker.io/library/ubuntu:24.04 as build

ENV DEBIAN_FRONTEND noninteractive

COPY ./scripts /app/scripts

RUN apt-get update && apt-get dist-upgrade -y 
RUN apt-get install cmake gcc g++ git make build-essential \
    libwayland-dev libx11-dev libxrandr-dev libxinerama-dev \
    libxcursor-dev libxi-dev libeigen3-dev libxkbcommon-dev \
    libpython3-dev libgl-dev clang-14 clang++-14 xorg-dev \
    gnupg lsb-release wget ca-certificates curl -y --no-install-recommends 

# Add drake installation
#RUN /app/scripts/drake_install.sh

# TODO Add non-root user

# TODO Clean up apt cache
# RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* 

# TODO Build project
# Create clean env with build artifacts
# Build project

#ENTRYPOINT ["/app/scripts/drake_install.sh"]
#CMD ["/app/build/safe_learning"]
