FROM docker.io/library/ros:jazzy-ros-base as build

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /install
COPY ./scripts /install/scripts

RUN apt-get update && apt-get dist-upgrade -y 
RUN apt-get install cmake gcc-14 g++-14 git make build-essential \
    libwayland-dev libx11-dev libxrandr-dev libxinerama-dev \
    libxcursor-dev libxi-dev libeigen3-dev libxkbcommon-dev \
    libpython3-dev libgl-dev libcurl4-openssl-dev libssl-dev libpsl-dev \
    nlohmann-json3-dev clang-14 clang++-14 xorg-dev ninja-build \
    gnupg lsb-release wget ca-certificates curl unzip jq locate nano -y --no-install-recommends 

# Add drake installation
RUN ls -lah && ls -lah /install && ./scripts/drake_install.sh


# TODO Add non-root user

# TODO Clean up apt cache
# RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* 

# TODO Build project
# Create clean env with build artifacts
# Build project


WORKDIR /app

#ENTRYPOINT ["/app/scripts/drake_install.sh"]
#CMD ["/app/build/safe_learning"]
