FROM docker.io/library/ros:jazzy-ros-base as build

ENV DEBIAN_FRONTEND noninteractive
# TODO Add non-root user
ARG USERNAME=ros_user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

WORKDIR /install
COPY ./scripts /install/scripts

RUN apt-get update && apt-get dist-upgrade -y 
RUN apt-get install cmake gcc-14 g++-14 git make build-essential \
    libwayland-dev libx11-dev libxrandr-dev libxinerama-dev \
    libxcursor-dev libxi-dev libeigen3-dev libxkbcommon-dev \
    libpython3-dev libgl-dev libcurl4-openssl-dev libssl-dev libpsl-dev \
    nlohmann-json3-dev clang-14 clang++-14 xorg-dev ninja-build \
    python3-pip ros-jazzy-example-interfaces gdbserver \
    nvidia-driver-580 gnupg lsb-release wget ca-certificates curl unzip jq locate nano -y --no-install-recommends 

# Add drake installation
RUN ls -lah && ls -lah /install && ./scripts/drake_install.sh


# Delete user if it exists in container (e.g Ubuntu Noble: ubuntu)
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
RUN apt-get update

# TODO: readd
#USER $USERNAME

# TODO temporary global install
RUN python3 -m pip install gymnasium[classic-control] mujoco imageio --break-system-packages \
&& python3 -m pip install torch -i https://download.pytorch.org/whl/cpu --break-system-packages 

# TODO Clean up apt cache
# RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* 

# TODO Build project
# Create clean env with build artifacts
# Build project


WORKDIR /app
# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************

# [Optional] Set the default user. Omit if you want to keep the default as root.
ENV SHELL /bin/bash
CMD ["/bin/bash"]

#CMD ["/app/build/safe_learning"]
